language: java
jdk:
  - oraclejdk8
docker:
  - docker1.12
refresh_token: hello
build:
  app_version: "mvn -q -Dexec.executable='echo' -Dexec.args='${projects.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec"
  script:
    - mvn clean install -Dmaven.test.skip=true
package:
  - type: docker
    docker_file: Dockerfile
    registry_uri: hub.fenxibao.com
    image_name: sample/node-wechatbelle
    image_tag: ${APP_VERSION}-${TIMESTAMP}
compose:
  - type: service
    service_file: .service.yml
